### ISSUE TITLE
Неверный расчет баланса, при пополнении отрицательного баланса.

### ISSUE THREAD

**Issue by JuliyaSvetlakova** [JuliyaSvetlakova/javaqa-team-diplom-2#10]
# Описание
Неверный расчет итогового баланса, при пополнении отрицательного баланса.

# Локация дефекта
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65 
# Шаги воспроизведения
1.	Создать объект класса CreditAccount с *начальным балансом* 1, *кредитным лимитом* 5_000 и *ставкой кредитования* 15.
2.	Совершить оплату на сумму 2
3.	Пополнить счет на сумму 3_000
4.	Запустить программу
5.	Посмотреть на вывод консоли
*Ожидаемый результат*:  2_999
*Фактический результат*: 3_000

# Тест на дефект
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L203 
# Скриншот
![image](https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/assets/133027664/ba5f9755-2618-4bc5-b1b3-4236eb186985)
# Окружение
**Операционная система:** Windows 10
**IDE:** ntelliJ IDEA 2023.1.2 (Community Edition)
**Java:** OpenJDK 11

**Comment by natalikazakova87** [comment]
ошибка исправлена
