### ISSUE TITLE
Начисление процентов по кредиту при положительном балансе.

### ISSUE THREAD

**Issue by JuliyaSvetlakova** [JuliyaSvetlakova/javaqa-team-diplom-2#11]
# Описание
Неверный расчет процентов по кредиту при положительном балансе.

# Локация дефекта
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82 
# Шаги воспроизведения
1.	Создать объект класса CreditAccount с *начальным балансом* 200, *кредитным лимитом* 5_000 и *ставкой кредитования* 15.
2.	Рассчитать проценты
3.	Запустить программу
4.	Посмотреть на вывод консоли
*Ожидаемый результат*:  0
*Фактический результат*: 30

# Тест на дефект
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L262 
# Скриншот
![image](https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/assets/133027664/4b63e1c3-1b0c-45db-8898-39643567dad1)
# Окружение
**Операционная система:** Windows 10
**IDE:** ntelliJ IDEA 2023.1.2 (Community Edition)
**Java:** OpenJDK 11

**Comment by natalikazakova87** [comment]
ошибка исправлена
