### ISSUE TITLE
Отсутствует класс исключения IllegalArgumentException для кредитного лимита.

### ISSUE THREAD

**Issue by JuliyaSvetlakova** [JuliyaSvetlakova/javaqa-team-diplom-2#13]
# Описание
Отсутствует класс исключения IllegalArgumentException для переменной  creditLimit.

# Локация дефекта
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/b10aa2b6b0ddcab2cc16c10cb247d43916e25c7f/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19 
# Шаги воспроизведения
1.	Создать метод Assertions.assertThrows с первым параметром IllegalArgumentException.class и вторым параметром нового класса CreditAccount с *начальным балансом* 0, *кредитным лимитом*  -1  и *ставкой кредитования* 15 .
2.	Запустить программу
3.	Посмотреть на вывод консоли
*Ожидаемый результат*: В консоли выводится сообщение ***Process finished with exit code 0***
*Фактический результат*: В консоли выводится сообщение ***org.opentest4j.AssertionFailedError: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown***

# Тест на дефект
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/b10aa2b6b0ddcab2cc16c10cb247d43916e25c7f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L71 
# Скриншот
![image](https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/assets/133027664/282da49e-cf54-4e44-989a-a273cc54c60d)
# Окружение
**Операционная система:** Windows 10
**IDE:** ntelliJ IDEA 2023.1.2 (Community Edition)
**Java:** OpenJDK 11

**Comment by natalikazakova87** [comment]
Ошибка исправлена
