### ISSUE TITLE
Отсутствует класс исключения IllegalArgumentException когда InitialBalance<MinBalance сберегательного счёта.

### ISSUE THREAD

**Issue by natalikazakova87** [JuliyaSvetlakova/javaqa-team-diplom-2#17]
# Описание
Отсутствует класс исключения IllegalArgumentException для  InitialBalance<MinBalance

# Локация дефекта
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/883911589c34a1c235bb69bd0b7011bf7a694ce9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Создать метод Assertions.assertThrows с первым параметром IllegalArgumentException.class и вторым параметром нового класса SavingAccount с начальным балансом 500, минимальным балансом 1_000, максимальным балансом 10_000 и ставкой кредитования 5.
1. Запустить программу
1. Посмотреть на вывод консоли
Ожидаемый результат: В консоли выводится сообщение Process finished with exit code 0
Фактический результат: В консоли выводится сообщение org.opentest4j.AssertionFailedError: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.

# Тест на дефект
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/883911589c34a1c235bb69bd0b7011bf7a694ce9/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L105

# Скриншот
![image](https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/assets/132995732/e87a75df-dd9e-4bee-9b59-f0b1de111dc5)

# Окружение
* **Операционная система**: Windows 10 Pro
* **IDE**: Intellij IDEA 2020.2 (Community Edition)
* **Java**: OpenJDK 11

**Comment by JuliyaSvetlakova** [comment]
Ошибка исправлена
