### ISSUE TITLE
Отсутствует возможность установления нулевой ставки кредитования для расчёта долга за отрицательный баланс.

### ISSUE THREAD

**Issue by JuliyaSvetlakova** [JuliyaSvetlakova/javaqa-team-diplom-2#2]
# Описание
Отсутствует возможность установления нулевого значения для переменной rate.

# Локация дефекта
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20 

# Шаги воспроизведения
1.	Создать объект класса CreditAccount с *начальным балансом* 0, *кредитным лимитом* 5_000 и *ставкой кредитования* 0.
2.	Запустить программу
3.	Посмотреть на вывод консоли
*Ожидаемый результат*: В консоли выводится сообщение ***Process finished with exit code 0***
*Фактический результат*: В консоли выводится сообщение *** java.lang.IllegalArgumentException: Накопительная ставка не может быть отрицательной, а у вас: 0***

# Тест на дефект
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L22 
# Скриншот
![image](https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/assets/133027664/4e2f4afa-1bac-476d-a053-7ce027f4fcc3)

# Окружение
**Операционная система:** Windows 10
**IDE:** ntelliJ IDEA 2023.1.2 (Community Edition)
**Java:** OpenJDK 11

**Comment by natalikazakova87** [comment]
ошибка исправлена
