### ISSUE TITLE
Неверный расчет сберегательного баланса, при сумме покупки превышающей размер баланса сберегательного счета.

### ISSUE THREAD

**Issue by natalikazakova87** [JuliyaSvetlakova/javaqa-team-diplom-2#20]
# Описание
Неверный расчет остаточного баланса, при сумме покупки превышающей размер текущего баланса.

# Локация дефекта
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/883911589c34a1c235bb69bd0b7011bf7a694ce9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Создать объект класса SavingAccount с начальным балансом 2_000, минимальным балансом 2_000, максимальным балансом 10_000, ставкой кредита 5.
1. Совершить оплату на сумму 3_500.
1. Запустить программу
1. Посмотреть на вывод консоли
Ожидаемый результат: 2_000
Фактический результат: - 1_500

# Тест на дефект
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/883911589c34a1c235bb69bd0b7011bf7a694ce9/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L165

# Скриншот
![image](https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/assets/132995732/a6795d9f-1436-462f-bedd-e44c452ccdb2)

# Окружение
* **Операционная система**: Windows 10
* **IDE**: ntelliJ IDEA 2023.1.2 (Community Edition)
* **Java**: OpenJDK 11

**Comment by JuliyaSvetlakova** [comment]
Ошибка исправлена
