### ISSUE TITLE
Неверный расчет баланса, при пополнении положительного баланса сберегательного счета. 

### ISSUE THREAD

**Issue by natalikazakova87** [JuliyaSvetlakova/javaqa-team-diplom-2#21]
# Описание
Неверный расчет итогового баланса, при пополнении положительного баланса.

# Локация дефекта
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/883911589c34a1c235bb69bd0b7011bf7a694ce9/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения
1. Создать объект класса SavingAccount с начальным балансом 2_000, минимальным балансом 1_000, максимальным балансом 10_000, ставкой кредитования 5.
1. Пополнить счет на сумму 3_000.
1. Запустить программу
1. Посмотреть на вывод консоли
Ожидаемый результат: 5_000
Фактический результат: 3_000

# Тест на дефект
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/883911589c34a1c235bb69bd0b7011bf7a694ce9/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L214

# Скриншот
![image](https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/assets/132995732/77a11887-1da6-4154-a016-8dce32926397)

# Окружение
* **Операционная система**: Windows 10
* **IDE**: ntelliJ IDEA 2023.1.2 (Community Edition)
* **Java**: OpenJDK 11

**Comment by JuliyaSvetlakova** [comment]
Ошибка исправлена
