### ISSUE TITLE
Неверный расчет баланса, при сумме покупки превышающей размер баланса, но не выходящей за кредитный лимит.

### ISSUE THREAD

**Issue by JuliyaSvetlakova** [JuliyaSvetlakova/javaqa-team-diplom-2#5]
# Описание
Неверный расчет остаточного баланса, при сумме покупки превышающей размер текущего баланса, но не выходящей за кредитный лимит.

# Локация дефекта
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40 
# Шаги воспроизведения
1.	Создать объект класса CreditAccount с *начальным балансом* 3_000, *кредитным лимитом* 5_000 и *ставкой кредитования* 15.
2.	Совершить оплату на сумму 7_999.
3.	Запустить программу
4.	Посмотреть на вывод консоли
*Ожидаемый результат*:  - 4_999
*Фактический результат*: - 7_999

# Тест на дефект
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L107 

# Скриншот
![image](https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/assets/133027664/6a6551e8-7024-4060-ba80-7b0a1f4e97f1)
# Окружение
**Операционная система:** Windows 10
**IDE:** ntelliJ IDEA 2023.1.2 (Community Edition)
**Java:** OpenJDK 11

**Comment by natalikazakova87** [comment]
ошибка исправлена
