### ISSUE TITLE
Неверный расчет баланса, при сумме покупки превышающей размер баланса и размер кредитного лимита.

### ISSUE THREAD

**Issue by JuliyaSvetlakova** [JuliyaSvetlakova/javaqa-team-diplom-2#6]
# Описание
Неверный расчет остаточного баланса, при сумме покупки превышающей размер текущего баланса и размер кредитного лимита.

# Локация дефекта
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40 
# Шаги воспроизведения
1.	Создать объект класса CreditAccount с *начальным балансом* 3_000, *кредитным лимитом* 5_000 и *ставкой кредитования* 15.
2.	Совершить оплату на сумму 8_001.
3.	Запустить программу
4.	Посмотреть на вывод консоли
*Ожидаемый результат*:  3_000
*Фактический результат*: - 5_001

# Тест на дефект
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L117 
# Скриншот
![image](https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/assets/133027664/49c35f68-38d0-4cfa-be91-27b9381ed8a9)
# Окружение
**Операционная система:** Windows 10
**IDE:** ntelliJ IDEA 2023.1.2 (Community Edition)
**Java:** OpenJDK 11

**Comment by natalikazakova87** [comment]
ошибка исправлена
