### ISSUE TITLE
Неверный расчет баланса, при сумме покупки, не превышающей размер баланса.

### ISSUE THREAD

**Issue by JuliyaSvetlakova** [JuliyaSvetlakova/javaqa-team-diplom-2#7]
# Описание
Неверный расчет остаточного баланса, при сумме покупки, не превышающей размер текущего баланса.

# Локация дефекта
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40 
# Шаги воспроизведения
1.	Создать объект класса CreditAccount с *начальным балансом* 3_000, *кредитным лимитом* 5_000 и *ставкой кредитования* 15.
2.	Совершить оплату на сумму 2_999.
3.	Запустить программу
4.	Посмотреть на вывод консоли
*Ожидаемый результат*:  1
*Фактический результат*: - 2_999

# Тест на дефект
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L127 
# Скриншот
![image](https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/assets/133027664/40b4e566-ec2d-4239-bd2b-8715ece73596)
# Окружение
**Операционная система:** Windows 10
**IDE:** ntelliJ IDEA 2023.1.2 (Community Edition)
**Java:** OpenJDK 11

**Comment by natalikazakova87** [comment]
ошибка исправлена
