### ISSUE TITLE
Неверный расчет баланса, при пополнении положительного баланса.

### ISSUE THREAD

**Issue by JuliyaSvetlakova** [JuliyaSvetlakova/javaqa-team-diplom-2#9]
# Описание
Неверный расчет итогового баланса, при пополнении положительного баланса.

# Локация дефекта
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65 
# Шаги воспроизведения
1.	Создать объект класса CreditAccount с *начальным балансом* 1, *кредитным лимитом* 5_000 и *ставкой кредитования* 15.
2.	Пополнить счет на сумму 3_000.
3.	Запустить программу
4.	Посмотреть на вывод консоли
*Ожидаемый результат*:  3_001
*Фактический результат*: 3_000

# Тест на дефект
https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/blob/8c9146a34c0973d0bfd7a5f8391bc2a546e7041e/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L191 
# Скриншот
![image](https://github.com/JuliyaSvetlakova/javaqa-team-diplom-2/assets/133027664/41bdeb64-f572-4890-a0e9-1c1b207ce15d)
# Окружение
**Операционная система:** Windows 10
**IDE:** ntelliJ IDEA 2023.1.2 (Community Edition)
**Java:** OpenJDK 11

**Comment by natalikazakova87** [comment]
ошибка исправлена
